---
# tasks file for deploy_wordpress_phpmyadmin
- name: Install packages
  yum: name={{ packages }}

- name: Install mysql
  yum: name={{ mysql_packages }}

- name: Install PHP
  yum: name={{ php_packages }}

- name: Restart apache
  service: name=httpd state=started enabled=yes

  #- name: Copy phpMyAdmin
  # copy:
  # src: phpMyAdmin-5.1.1-all-languages.tar.gz
  # dest: /home/ec2-user

- name: Make Directory for phpmyadmin
  ansible.builtin.file:
      path: /usr/share/phpmyadmin
      state: directory
      mode: '777'
      owner: apache
      group: apache

- name: Extract Archive phpMyAdmin
  ansible.builtin.unarchive:
        src: https://files.phpmyadmin.net/phpMyAdmin/5.1.1/phpMyAdmin-5.1.1-all-languages.tar.gz
        dest: /usr/share/phpmyadmin
        owner: apache
        group: apache
        extra_opts:
          - --strip=1
        remote_src: yes

- name: Delete Archve
  file:
    path: /home/ec2-user/phpMyAdmin-5.1.1-all-languages.zip
    state: absent

- name: Make Dirrectory for temp files
  ansible.builtin.file: path={{ item }} state=directory owner=apache group=apache mode=777
  loop:
   - "/var/lib/phpmyadmin/tmp"
   - "/etc/phpmyadmin"

     #- name: Create directory for phpMyAdmin configuration files
     #  ansible.builtin.file:
     #   path: /etc/phpmyadmin/
     # state: directory
     #    mode: '0755'
     # owner: apache
     # group: apache

- name: Copy configuration file
  copy: src={{ item }} dest={{ conf_folder }}  owner=apache group=apache mode=0755
  loop:
   - "config.inc.php"

- name: Add phpmyamin.conf for apache
  copy: src={{ item }} dest={{ confd_folder }} owner=apache group=apache mode=0755
  loop:
   - "phpmyadmin.conf"

- name: Start MariaDB
  service:
     name: mariadb
     enabled: true
     state: started

- name: Mysql Root Pass
  mysql_user: name=root password="qweqwe"

- name: Restart Apache
  service: name=httpd state=restarted
                                                                          
